### ISSUE TITLE
how to do a paragraph break in the tooltip html source code in Jupyter notebook ?

### ISSUE THREAD

**Issue by RicardoGomesIST** [UnfoldedInc/pydeck#16]
Hi, this should be simple but I cannot get it
I am using pydeck to export a polygon layer. Work perfectly but I have a long description on the tooltip: 

I have this working:

`tooltip = {"html": "<b> Building characterization <br /> <b> & nbsp; Height of the building (m): </b> {height_ag} <br />","style": {"backgroundColor": "steelblue","color": "white"} }`

But if I wish a very long description it helps to be able to do a paragraph mark on the source text (be able to organize the different variables that will be shown on the map). 
IF I just do a paragraph the html code does not work - it stops being red colored. So the code below does not work:

```
tooltip = {"html": "<b> Building characterization <br /> 
                                <b> & nbsp; Height of the building (m): </b> {height_ag} <br />",
                                "style": {"backgroundColor": "steelblue","color": "white"} }`

```

**Comment by kylebarron** [comment]
The main pydeck repo is at https://github.com/visgl/deck.gl/ and you should ask your questions there. This repo is only for the documentation website

**Comment by RicardoGomesIST** [comment]
sorry, thank you
